"""empty message

Revision ID: 07a04e458bc3
Revises: eb771dc9d825
Create Date: 2024-12-09 20:16:35.511727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a04e458bc3'
down_revision = 'eb771dc9d825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('online_status', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('online_status')

    # ### end Alembic commands ###
