"""Updated Sales Model

Revision ID: 193b7af7c8bd
Revises: 
Create Date: 2024-12-03 11:24:25.965081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '193b7af7c8bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuisine_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('payment_mode', sa.Enum('COD', 'UPI', 'Credit Card', 'Debit Card'), nullable=True))
        batch_op.create_foreign_key(None, 'food_items', ['item_id'], ['id'])
        batch_op.create_foreign_key(None, 'cuisines', ['cuisine_id'], ['id'])
        batch_op.drop_column('price')
        batch_op.drop_column('cuisine')
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('cuisine', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('payment_mode')
        batch_op.drop_column('item_id')
        batch_op.drop_column('cuisine_id')

    # ### end Alembic commands ###
