"""empty message

Revision ID: 229e87cdf76a
Revises: a0b7c8f1ecab
Create Date: 2024-11-18 16:10:08.880854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '229e87cdf76a'
down_revision = 'a0b7c8f1ecab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint('admins_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('admins_ibfk_4', type_='foreignkey')
        batch_op.drop_constraint('admins_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('admins_ibfk_2', type_='foreignkey')
        batch_op.drop_column('super_distributor_id')
        batch_op.drop_column('manager_id')
        batch_op.drop_column('kitchen_id')
        batch_op.drop_column('distributor_id')

    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('super_distributor', sa.Integer(), nullable=True))
        batch_op.drop_constraint('distributors_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'super_distributors', ['super_distributor'], ['id'])
        batch_op.drop_column('kitchen_id')

    with op.batch_alter_table('kitchens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distributor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'distributors', ['distributor_id'], ['id'])

    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.drop_constraint('managers_ibfk_1', type_='foreignkey')
        batch_op.drop_column('super_distributor_id')

    with op.batch_alter_table('super_distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('super_distributors_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'managers', ['manager_id'], ['id'])
        batch_op.drop_column('distributor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('super_distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distributor_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('super_distributors_ibfk_1', 'distributors', ['distributor_id'], ['id'])
        batch_op.drop_column('manager_id')

    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('super_distributor_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('managers_ibfk_1', 'super_distributors', ['super_distributor_id'], ['id'])

    with op.batch_alter_table('kitchens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('distributor_id')

    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kitchen_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('distributors_ibfk_1', 'kitchens', ['kitchen_id'], ['id'])
        batch_op.drop_column('super_distributor')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distributor_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('kitchen_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('manager_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('super_distributor_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('admins_ibfk_2', 'kitchens', ['kitchen_id'], ['id'])
        batch_op.create_foreign_key('admins_ibfk_1', 'distributors', ['distributor_id'], ['id'])
        batch_op.create_foreign_key('admins_ibfk_4', 'super_distributors', ['super_distributor_id'], ['id'])
        batch_op.create_foreign_key('admins_ibfk_3', 'managers', ['manager_id'], ['id'])

    # ### end Alembic commands ###
