"""empty message

Revision ID: 337ed3acae1c
Revises: 229e87cdf76a
Create Date: 2024-11-19 11:15:56.544060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '337ed3acae1c'
down_revision = '229e87cdf76a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', mysql.LONGBLOB(), nullable=True))

    with op.batch_alter_table('cuisines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', mysql.LONGBLOB(), nullable=True))

    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', mysql.LONGBLOB(), nullable=True))

    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', mysql.LONGBLOB(), nullable=True))

    with op.batch_alter_table('kitchens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', mysql.LONGBLOB(), nullable=True))

    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.VARCHAR(length=255),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    with op.batch_alter_table('super_distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', mysql.LONGBLOB(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('super_distributors', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.LONGBLOB(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('kitchens', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('cuisines', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
