"""empty message

Revision ID: 4ae95e1d5e53
Revises: 337ed3acae1c
Create Date: 2024-11-20 12:28:53.291840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae95e1d5e53'
down_revision = '337ed3acae1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('activated', 'deactivated'), nullable=True))

    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('activated', 'deactivated'), nullable=True))

    with op.batch_alter_table('kitchens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('activated', 'deactivated'), nullable=True))

    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('activated', 'deactivated'), nullable=True))

    with op.batch_alter_table('super_distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('activated', 'deactivated'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('super_distributors', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('kitchens', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
