"""Changes in Kitchen password

Revision ID: 4d58e627b577
Revises: 9fcd4970625c
Create Date: 2024-11-15 11:56:24.503950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d58e627b577'
down_revision = '9fcd4970625c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kitchens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kitchens', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
