"""empty message

Revision ID: 5b3ec57316e5
Revises: e8481aac01d3
Create Date: 2024-12-21 22:10:08.309979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b3ec57316e5'
down_revision = 'e8481aac01d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('super_distributor', sa.Integer(), nullable=True))
        batch_op.drop_constraint('distributors_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'super_distributors', ['super_distributor'], ['id'])
        batch_op.drop_column('super_distributor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('super_distributor_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('distributors_ibfk_3', 'super_distributors', ['super_distributor_id'], ['id'])
        batch_op.drop_column('super_distributor')

    # ### end Alembic commands ###
