"""Removed Manager ID columns from distributors and kitchens

Revision ID: 6966fb648915
Revises: f138ec6b9503
Create Date: 2024-12-26 11:06:38.334923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6966fb648915'
down_revision = 'f138ec6b9503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.drop_constraint('distributors_ibfk_2', type_='foreignkey')
        batch_op.drop_column('manager_id')

    with op.batch_alter_table('kitchens', schema=None) as batch_op:
        batch_op.drop_constraint('kitchens_ibfk_2', type_='foreignkey')
        batch_op.drop_column('manager_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kitchens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('kitchens_ibfk_2', 'managers', ['manager_id'], ['id'])

    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('distributors_ibfk_2', 'managers', ['manager_id'], ['id'])

    # ### end Alembic commands ###
