"""empty message

Revision ID: 7037c12aa45b
Revises: d3652732b104
Create Date: 2024-12-20 23:46:25.424151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7037c12aa45b'
down_revision = 'd3652732b104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.drop_constraint('distributors_ibfk_3', type_='foreignkey')
        batch_op.drop_column('super_distributor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('super_distributor_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('distributors_ibfk_3', 'super_distributors', ['super_distributor_id'], ['id'])

    # ### end Alembic commands ###
