"""empty message

Revision ID: 8ee3cfbc3a6c
Revises: d3878b14624e
Create Date: 2024-11-06 11:40:56.381372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ee3cfbc3a6c'
down_revision = 'd3878b14624e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
