"""Added Royalty Model

Revision ID: 937259e35d7a
Revises: 
Create Date: 2024-12-27 10:32:07.874161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937259e35d7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('royalty_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('royalty_percentage', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('royalty_wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('royalty_amount', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('royalty_wallet')
    op.drop_table('royalty_settings')
    # ### end Alembic commands ###
