"""Fix foreign key and relationship between Distributor and SuperDistributor

Revision ID: 98886abc8548
Revises: 
Create Date: 2024-12-20 11:04:33.280328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98886abc8548'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.drop_constraint('distributors_ibfk_1', type_='foreignkey')
        batch_op.drop_column('super_distributor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('super_distributor', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('distributors_ibfk_1', 'super_distributors', ['super_distributor'], ['id'])

    # ### end Alembic commands ###
