"""empty message

Revision ID: 98b523b86b46
Revises: 98886abc8548
Create Date: 2024-12-20 15:08:52.790826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b523b86b46'
down_revision = '98886abc8548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('super_distributor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'super_distributors', ['super_distributor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('super_distributor_id')

    # ### end Alembic commands ###
