"""Added pin code fild in kitchen model file

Revision ID: 9fcd4970625c
Revises: 
Create Date: 2024-11-15 11:36:57.668919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fcd4970625c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kitchens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_code', sa.String(length=6), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kitchen_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('orders_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'kitchens', ['kitchen_id'], ['id'])
        batch_op.drop_column('restaurant_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('orders_ibfk_1', 'kitchens', ['restaurant_id'], ['id'])
        batch_op.drop_column('kitchen_id')

    with op.batch_alter_table('kitchens', schema=None) as batch_op:
        batch_op.drop_column('pin_code')

    # ### end Alembic commands ###
