"""empty message

Revision ID: a0b7c8f1ecab
Revises: 1cbe5af7bd87
Create Date: 2024-11-18 10:58:22.960944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b7c8f1ecab'
down_revision = '1cbe5af7bd87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kitchen_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'kitchens', ['kitchen_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('kitchen_id')

    # ### end Alembic commands ###
