"""empty message

Revision ID: e8481aac01d3
Revises: 7037c12aa45b
Create Date: 2024-12-20 23:52:26.180556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8481aac01d3'
down_revision = '7037c12aa45b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('super_distributor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'super_distributors', ['super_distributor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('super_distributor_id')

    # ### end Alembic commands ###
