"""empty message

Revision ID: f138ec6b9503
Revises: 5b3ec57316e5
Create Date: 2024-12-25 12:49:04.305078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f138ec6b9503'
down_revision = '5b3ec57316e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_constraint('activity_logs_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('activity_logs_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('activity_logs_ibfk_5', type_='foreignkey')
        batch_op.drop_constraint('activity_logs_ibfk_4', type_='foreignkey')
        batch_op.drop_constraint('activity_logs_ibfk_1', type_='foreignkey')
        batch_op.drop_column('admin_id')
        batch_op.drop_column('distributor_id')
        batch_op.drop_column('manager_id')
        batch_op.drop_column('kitchen_id')
        batch_op.drop_column('super_distributor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('super_distributor_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('kitchen_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('manager_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('distributor_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('admin_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('activity_logs_ibfk_1', 'admins', ['admin_id'], ['id'])
        batch_op.create_foreign_key('activity_logs_ibfk_4', 'managers', ['manager_id'], ['id'])
        batch_op.create_foreign_key('activity_logs_ibfk_5', 'super_distributors', ['super_distributor_id'], ['id'])
        batch_op.create_foreign_key('activity_logs_ibfk_2', 'distributors', ['distributor_id'], ['id'])
        batch_op.create_foreign_key('activity_logs_ibfk_3', 'kitchens', ['kitchen_id'], ['id'])

    # ### end Alembic commands ###
